auth_enabled: false

server:
  http_listen_port: 3100


storage_config:
  aws:
    s3: s3://your-bucket-name/loki-logs
    access_key_id: YOUR_AWS_ACCESS_KEY
    secret_access_key: YOUR_AWS_SECRET_KEY
    region: us-east-1
    insecure: false
    bucketnames: your-bucket-name
    s3forcepathstyle: false
    s3url: https://s3.amazonaws.com
  boltdb_shipper:
    active_index_directory: /loki/index
    shared_store: filesystem
    cache_location: /loki/cache

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_chunk_age: 1h
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

schema_config:
  configs:
    - from: 2022-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

